"""empty message

Revision ID: 9c8d1d74adf5
Revises: 4145d15bb5bc
Create Date: 2025-04-18 21:47:38.166619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8d1d74adf5'
down_revision: Union[str, None] = '4145d15bb5bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('original_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['original_post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'original_post_id')
    # ### end Alembic commands ###
