"""fix Likes

Revision ID: ef58c6139f85
Revises: 502d5cc9398c
Create Date: 2025-04-19 19:41:07.173627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef58c6139f85'
down_revision: Union[str, None] = '502d5cc9398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('unique_user_post_like', 'likes', type_='unique')
    op.create_index('uq_likes_user_comment', 'likes', ['user_id', 'comment_id'], unique=True, postgresql_where=sa.text('post_id IS NULL'))
    op.create_index('uq_likes_user_post', 'likes', ['user_id', 'post_id'], unique=True, postgresql_where=sa.text('comment_id IS NULL'))
    op.create_foreign_key(None, 'likes', 'comments', ['comment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_index('uq_likes_user_post', table_name='likes', postgresql_where=sa.text('comment_id IS NULL'))
    op.drop_index('uq_likes_user_comment', table_name='likes', postgresql_where=sa.text('post_id IS NULL'))
    op.create_unique_constraint('unique_user_post_like', 'likes', ['user_id', 'post_id'])
    op.alter_column('likes', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('likes', 'comment_id')
    # ### end Alembic commands ###
