DATABASE_URL: postgresql+asyncpg://network_events:network_events@192.168.1.114:5432/network_events
REDIS_URL: redis://192.168.1.118:6379/0
RABBITMQ_URL: amqp://network_events:network_events@192.168.1.117:5672//

# ======== Настройки для Auth Proxy ========

AUTH_PROXY_URL: http://register:8010

# Для сервиса auth-proxy

REQUEST_TIMEOUT: 5

