version: "3.8"

services:
  recommendations:
    build: .
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user-service
    networks:
      - backend


networks:
  backend:
    external: true