variables:
  DOCKER_IMAGE_NAME: registr-dev
  DOCKER_REGISTRY: nexus.youteam.space:5000

stages:
  - build
  - push

before_script:
  - export DOCKER_TAG=$(date +%d.%m.%Y)
  - echo "Логинимся в Nexus..."
  - echo "$NEXUS_PASSWORD" | docker login -u "$NEXUS_USERNAME" --password-stdin $DOCKER_REGISTRY || exit 1

build_image:
  stage: build
  tags:
    - docker
  script:
    - echo "Собираем образ с тегом $DOCKER_TAG..."
    # Вариант 1: Используем стандартный build
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
    # ИЛИ Вариант 2: Явно используем buildx
    # - docker buildx build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG --load .
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_TAG $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG
  only:
    - dev

push_to_nexus:
  stage: push
  tags:
    - docker
  script:
    - echo "Пушим $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG..."
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$DOCKER_TAG
  only:
    - dev
