env: "local"
is_file_log_output: false
storage_path: postgres://evans:evans@localhost:8012/postgres?sslmode=disable

postgres:
  host: localhost
  port: 8012
  user: evans
  password: evans
  name: postgres
  use_ssl: disable

http_server: 
  host: localhost
  port: 8010
  read_header_timeout: 5s
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s

redis:
  host: redis
  port: 6379
  password: redis
  ttl: 5m
  db_number: 0
  maxmemory: 200mb
