env: "dev"
is_file_log_output: false
storage_path: postgres://evans:evans@postgres:8012/postgres?sslmode=disable

postgres:
  host: postgres
  port: 8012
  user: evans
  password: evans
  name: postgres
  use_ssl: disable

http_server:
  host: 0.0.0.0
  port: 8010
  read_header_timeout: 5s
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 60s
  allowed_domains_cors:
    - "http://localhost:8010"
    - "http://localhost:5173"
    - "http://localhost:5174"

redis:
  host: redis
  port: 8011
  password: evans
  ttl: 15m
  db_number: 0
  maxmemory: 200mb
