"""Create all tables

Revision ID: d59ab5559d64
Revises: 2ffd59161228
Create Date: 2025-04-01 06:04:58.780714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ab5559d64'
down_revision = '2ffd59161228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
