"""fix id int -> str

Revision ID: 01aab91407c9
Revises: 17a08f034615
Create Date: 2025-05-25 12:28:15.847663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01aab91407c9'
down_revision: Union[str, None] = '17a08f034615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group_members', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='ID пользователя',
               existing_nullable=False)
    op.alter_column('groups', 'creator_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='ID создателя',
               existing_nullable=True)
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='ID автора',
               existing_nullable=True)
    op.alter_column('posts', 'edited_by',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_comment='Кто редактировал',
               existing_nullable=True)
    op.add_column('users_cache', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users_cache', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.alter_column('users_cache', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_cache', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users_cache', 'last_name')
    op.drop_column('users_cache', 'first_name')
    op.alter_column('posts', 'edited_by',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='Кто редактировал',
               existing_nullable=True)
    op.alter_column('posts', 'author_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='ID автора',
               existing_nullable=True)
    op.alter_column('groups', 'creator_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='ID создателя',
               existing_nullable=True)
    op.alter_column('group_members', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_comment='ID пользователя',
               existing_nullable=False)
    # ### end Alembic commands ###
