DATABASE_URL: postgresql+asyncpg://user:password@db:5432/events_db
REDIS_URL: redis://:redis@redis:6379/0
RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672//

# ======== Настройки для Auth Proxy ========

AUTH_PROXY_URL: http://regserv:8010

# Для сервиса auth-proxy

REQUEST_TIMEOUT: 5

