# ======== Базовые настройки ========
POSTGRES_HOST=192.168.1.114
REDIS_HOST=192.168.1.118
RABBITMQ_HOST=192.168.117

POSTGRES_PORT=5432
RABBITMQ_PORT=5672
REDIS_PORT=6379

# ======== Настройки БД ========
POSTGRES_USER=interest_groups
POSTGRES_PASSWORD=interest_groups
POSTGRES_DB=interest_groups
DATABASE_URL=postgresql://interest_groups:interest_groups@192.168.1.114:5432/interest_groups


# ======== Настройки Redis ========
REDIS_PASSWORD=redis
REDIS_URL=redis://:redis@$192.168.1.118:6379/0

# ======== Настройки RabbitMQ ========
RABBITMQ_USER=interest_groups
RABBITMQ_PASS=interest_groups
RABBITMQ_VHOST=/
RABBITMQ_URL=amqp://interest_groups:interest_groups@192.168.1.117:5672/
RABBITMQ_TIMEOUT=10

# ======== Настройки для Auth Proxy ========
AUTH_PROXY_URL=http://register:8010
  # URL для обращения к auth-proxy
# Для сервиса auth-proxy
REQUEST_TIMEOUT=5

# ================
#ALLOWED_ORIGINS='["http://localhost:3000", "http://frontend.com"]'
CORS_ALLOW_CREDENTIALS=True
REQUIRE_SCOPES=True

# ======== Логирование ========
LOG_LEVEL=INFO
LOG_FORMAT=json



