"""empty message

Revision ID: c3e2042d8b8d
Revises:
Create Date: 2025-03-17 14:31:56.080597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c3e2042d8b8d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("profile_photo", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("work_experience", sa.String(), nullable=True),
        sa.Column("education", sa.String(), nullable=True),
        sa.Column("git_profile", sa.String(), nullable=True),
        sa.Column("tech_stack", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "purpose_cooperation",
            sa.Enum(
                "JOB_SEARCH",
                "PARTNERSHIP",
                "EXCHANGE_EXPERIENCE",
                name="purposecooperation",
            ),
            nullable=True,
        ),
        sa.Column("desired_salary", sa.Integer(), nullable=True),
        sa.Column("profile_privacy", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
