"""Added relationship between Group and Post

Revision ID: 0ecb392169be
Revises: 32b0f082b97b
Create Date: 2025-04-01 05:38:39.735814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecb392169be'
down_revision = '32b0f082b97b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
