"""Added creator relationship in Group

Revision ID: 2ffd59161228
Revises: 0ecb392169be
Create Date: 2025-04-01 05:43:50.953109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffd59161228'
down_revision = '0ecb392169be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
