version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - backend
    
  db:
    image: postgres:15
    container_name: test2db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    networks:
      - backend

    


networks:
  backend:
    driver: bridge