"""init migration

Revision ID: 3f9e36d39f93
Revises: 
Create Date: 2025-07-01 00:08:17.080700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9e36d39f93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Goodnes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('val_1', sa.Integer(), nullable=True),
    sa.Column('val_2', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Goodnes')
    # ### end Alembic commands ###
