"""create weight tables

Revision ID: 34afd0830d6f
Revises: 65e5777fc0f0
Create Date: 2025-05-12 12:26:58.931834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34afd0830d6f'
down_revision: Union[str, None] = '65e5777fc0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_weight',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.CheckConstraint('weight >= 0', name='chk_weight_non_negative'),
    sa.PrimaryKeyConstraint('user_id', 'author_id')
    )
    op.create_table('hashtag_weight',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.CheckConstraint('weight >= 0', name='chk_hashtag_weight_non_negative'),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'hashtag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hashtag_weight')
    op.drop_table('author_weight')
    # ### end Alembic commands ###
