"""fix Posts

Revision ID: 35c1fbe70bd1
Revises: 9c8d1d74adf5
Create Date: 2025-04-18 23:29:31.465620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c1fbe70bd1'
down_revision: Union[str, None] = '9c8d1d74adf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_original_post_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'posts', ['original_post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_original_post_id_fkey', 'posts', 'posts', ['original_post_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
