"""create posts likes attachments hashtags

Revision ID: 422726a3719b
Revises: 72274e689cb6
Create Date: 2025-04-09 21:45:28.546346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422726a3719b'
down_revision: Union[str, None] = '72274e689cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_name'), 'hashtags', ['name'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('attachment_path', sa.String(), nullable=False),
    sa.Column('caption', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='unique_user_post_like')
    )
    op.create_table('post_hashtag',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id'),
    sa.UniqueConstraint('post_id', 'hashtag_id', name='uix_post_hashtag')
    )
    op.create_index('ix_hashtag_id', 'post_hashtag', ['hashtag_id'], unique=False)
    op.create_index('ix_post_id', 'post_hashtag', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('posts', sa.Column('content', sa.String(length=20000), nullable=False))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'content')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'user_id')
    op.drop_index('ix_post_id', table_name='post_hashtag')
    op.drop_index('ix_hashtag_id', table_name='post_hashtag')
    op.drop_table('post_hashtag')
    op.drop_table('likes')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_hashtags_name'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
