"""empty message

Revision ID: 87f1d6408c0d
Revises: c3e2042d8b8d
Create Date: 2025-03-17 16:59:49.764582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "87f1d6408c0d"
down_revision: Union[str, None] = "c3e2042d8b8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "skills",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("users", "tech_stack")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "tech_stack",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "users",
        "skills",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
