"""empty message

Revision ID: bfd30aa47296
Revises: 87f1d6408c0d
Create Date: 2025-03-17 17:42:12.415973

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "bfd30aa47296"
down_revision: Union[str, None] = "87f1d6408c0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
