"""empty message

Revision ID: f630d904f5f5
Revises: 7acb33152ccb
Create Date: 2025-03-25 16:20:52.813414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f630d904f5f5"
down_revision: Union[str, None] = "7acb33152ccb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "purpose_cooperation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "purpose_cooperation",
            postgresql.ENUM(
                "JOB_SEARCH",
                "PARTNERSHIP",
                "EXCHANGE_EXPERIENCE",
                name="purposecooperation",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
