# ======== Базовые настройки ========
POSTGRES_HOST: db
REDIS_HOST: redis
RABBITMQ_HOST: rabbitmq

POSTGRES_PORT: 5432
RABBITMQ_PORT: 5672
REDIS_PORT: 6379

# ======== Настройки БД ========
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: interest_groups
DATABASE_URL: postgresql://postgres:postgres@db:5432/interest_groups

# ======== Настройки Redis ========
REDIS_PASSWORD: redis
REDIS_URL: redis://:redis@redis:6379/0

# ======== Настройки RabbitMQ ========
RABBITMQ_USER: user
RABBITMQ_PASS: password
RABBITMQ_VHOST: /
RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
RABBITMQ_TIMEOUT: 10

# ======== Настройки для Auth Proxy ========
AUTH_PROXY_URL: http://regserv:8010
REQUEST_TIMEOUT: 5

# ======== CORS/Безопасность ========
ALLOWED_ORIGINS:
  - http://localhost:3000
CORS_ALLOW_CREDENTIALS: true
REQUIRE_SCOPES: true

# ======== Логирование ========
LOG_LEVEL: INFO
LOG_FORMAT: json
